services:
  avito-pr-service:
    build: .
    container_name: avito-pr-service
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - avito-pr-network

  postgres:
    image: postgres:18
    restart: always
    container_name: avito-pr-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pg-data:/var/lib/postgresql
    networks:
      - avito-pr-network

volumes:
  pg-data:

networks:
  avito-pr-network: