services:
  avito-pr-service:
    build: .
    container_name: avito-pr-service
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      HTTP_PORT: ${HTTP_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      PG_POOL_MAX: ${PG_POOL_MAX}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_NAME: ${PG_NAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_USER: ${PG_USER}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - avito-pr-network

  postgres:
    image: postgres:18
    restart: always
    container_name: avito-pr-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - pg-data:/var/lib/postgresql
    networks:
      - avito-pr-network

volumes:
  pg-data:

networks:
  avito-pr-network: