services:
  avito-pr-service-test:
    build:
      context: .
    container_name: avito-pr-service-load-test
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    env_file:
      - .env.test
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${HTTP_PORT}/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - avito-pr-network-test

  postgres-test:
    image: postgres:18
    restart: always
    container_name: avito-pr-db-load-test
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - load_test_postgres_data:/var/lib/postgresql
    networks:
      - avito-pr-network-test

volumes:
  load_test_postgres_data:

networks:
  avito-pr-network-test: